BOARD_READ = '0'
BOARD_POST = '1'
BOARD_DENY = '2'
BOARD_ADMIN = '3'

TEAM_GUEST = 'GUEST'
TEAM_WELCOME = 'Welcome'
TEAM_USER = 'User'
TEAM_DENY_GLOBAL ='DenyGlobal'

TEAM_T_BOARD_DENY = '%sDeny'
TEAM_T_BOARD_BM   = '%sBM'

DEFAULT_BOARD_R_TEAM = [
    TEAM_GUEST, TEAM_WELCOME, TEAM_USER, 
    ]

DEFAULT_BOARD_W_TEAM = [
    TEAM_USER,
    ]

DEAFULT_BOARD_D_TEAM = [
    TEAM_DENY_GLOBAL,
    ]

DEAFULT_BOARD_X_TEAM = [
    ]
